name: "Bug Report"
description: "Bug report form for technical users."
title: ""
labels: ["bug"]
body:
- type: "markdown"
  attributes:
    value: "This form is for technical users to report bugs.\nNon-technical users can report bugs on the [Retro Rewind Discord Server](https://discord.gg/RetroRewind) in the bug-report channel.\n\nThis triaging is done to make it easier for the developers to work on the project, as bug reports from users are often invalid."
- type: "markdown"
  attributes:
    value: "### Reporting guidelines\n- Please only report bugs, that you were able to confirm are actually present.\n  - Examples for this are: Confirming it yourself ingame, receiving video/picture evidence etc.\n- Don't report My Stuff-related bugs unless it is a large scale issue affecting most users.\n  - Ineligible reports are, for example, when MenuSingles or Race files stop displaying properly after a RaceAssets/UIAssets etc. edit, which can be fixed by the mod editor\n  - Eligible reports may be, for example, if every user with a non-RR specialized Race.szs always crashes\n- Don't use this form for feature suggestions.\n  - Exceptions are when certain user experiences are so misleading, that they negatively affect most of RRs observable player base.\nBug reports not following these guidelines may be closed without explanation."
- type: "textarea"
  attributes:
    label: "Version"
    description: "What version was this bug originally found on?"
    placeholder: "v6.7"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Type of bug"
    description: "What type of bug is this?"
    placeholder: "such as Crash, UI, Visual, Gameplay etc."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Bug description"
    description: "Describe the bug in greater detail."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Reproduction steps"
    description: "Please explain here how to reproduce the bug. If you already resolved the crashdump, you can paste the stacktrace in here instead of uploading a crash.pul below."
  validations:
    required: true
- type: "upload"
  attributes:
    label: "Crashdump (Archive formats only)"
    description: "Please always request a crash.pul from users and provide it in the issue. The upload needs to be done in an archive format such as ZIP."
  validations:
    required: false
