name: "Track Problem"
description: "Track problem form for team members and contributors only!"
title: "[Track Problem]: "
labels: ["track"]
body:
- type: "markdown"
  attributes:
    value: "### Please include the name of the track in the title!\n\nThis form **only** serves Retro Rewind **team members and contributors** to report track problems for tracks made by team members.\n\nPeople outside of the team can report track problems for tracks made by team members on the [Retro Rewind Discord Server](https://discord.gg/RetroRewind) in the bug-report channel.\nTrack problems for tracks not made by team members should be reported to track authors directly, as the Retro Rewind Team does not edit tracks from other authors.\n\nThis triaging is done to make it easier for the developers to work on the project, as bug reports from users are often invalid."
- type: "markdown"
  attributes:
    value: "### Reporting guidelines\n- Please only report track problems, that you were able to confirm are actually present.\n  - Examples for this are: Confirming it yourself ingame, receiving video/picture evidence etc.\n- Don't use this form for design suggestions.\n  - Exceptions are when certain user experiences are so misleading, that they negatively affect most of RRs observable player base."
- type: "checkboxes"
  attributes:
    label: "Authorization check"
    description: "By checking this box, you agree that you are authorized to make a track problem report. If you are not authorized, your issue may be closed without explanation."
    options:
    - label: "Yes"
      required: true
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Version"
    description: "What game version was this track problem originally found on?"
    placeholder: "v6.7"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Track"
    description: "On what track and version was the problem found?"
    placeholder: "Retro Rewind Mansion, v1.23-hotfix2"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Author"
    description: "Who made the track?"
    placeholder: "ZPL, Gab"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Problem description"
    description: "Describe the problem in greater detail."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Reproduction steps"
    description: "Please explain here how to reproduce the problem, if applicable."
  validations:
    required: false
- type: "upload"
  attributes:
    label: "Upload footage"
    description: "If possible, upload footage of the issue occuring."
  validations:
    required: false
