name: "User Feature Submission Application"
description: "Apply to develop and submit a feature for Retro Rewind!"
title: "[Feature Submission Application]: "
labels: ["feature", "discussion"]
body:
- type: "markdown"
  attributes:
    value: "This form is open for everyone to apply to provide Retro Rewind with a new feature! Feel free to discuss your ideas on the [Retro Rewind Discord Server](https://discord.gg/RetroRewind) before making an application to make sure, that your application is high quality. The reason behind the developers not taking unapproved feature submissions can be found in the feature-suggestions channel on Discord."
- type: "markdown"
  attributes:
    value: "### Application guidelines\n- Please only submit features, that you expect a significant number of the broad Retro Rewind player base to adopt.\n  - Examples for this are: Prediction Removal, Competitive Matchmaking, Advanced Sound Settings\n  - If the feature would be one only used by a niche group of players, try to think bigger. Consider thinking a few steps ahead to make the feature useful for the broad Retro Rewind player base.\n  - Examples for exceptions are: Mii Heads in friend rooms, Disable Random Combo Button\n- Don't submit features, if you are going to take from other packs or if you are going to exclusively vibe-code them.\n- You are fine to submit fully vibe-coded feature under the following circumstance:\n  - You have to fully disclose this and still know what you're doing. You should know how to properly make and test your own implementation."
- type: "checkboxes"
  attributes:
    label: "Compliance check"
    description: "By checking this box, you agree that your request is following the application guidelines. If you are not following the guidelines, your issue may be closed without explanation."
    options:
    - label: "Yes"
      required: true
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Version"
    description: "What version is the pack on, at the time of making this suggestion?"
    placeholder: "v6.7"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Introduce yourself!"
    description: "Help us get to know you better."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Experience and reputation"
    description: "Please share your previous work and your most active socials."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Feature description"
    description: "What would the feature you're suggesting do?"
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Pitch"
    description: "What makes this feature stand out and be useful for the broad Retro Rewind player base?"
  validations:
    required: true
